<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Version>1.0.3</Version>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\arian.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="PDFsharp-WPF" Version="6.2.4" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12-pre20260709125052" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\arian-logo.png" />
    <Resource Include="Assets\arian.ico" />
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>

</Project>
